### PR TITLE
Fix infinite recursion in arg list

### LINKED ISSUE #2: `foo(a, b;` causes infinite recursion with regards to error recovery
`foo(a, b;` causes the parser to infinitely recurse when trying to recover.

 i presume this is because `b` will be parsed as an expr, then `args` will loop back and expect a comma, it does not see one so it goes on, then it tries to parse `;` as an expression. `;` is in the `EXPR_RECOVERY_SET` therefore it does not bump over the token. This might require explicit recovery set handling because recovery on `;` is very valuable but infinite recursion is unacceptable. A solution to this which does not mess with other recoveries will require a bit of thought.

### PR DESCRIPTION
**Pull request by Stupremee**
Resolves #2

### CODE REVIEW

**Comment by RDambrosio016** [comment]
The tests are created using inline `// test_err name` comments then generated with `cargo xtask codegen`, not manually, although the numbers on each test seem to create issues when making new tests. I will remove the numbers, then we should keep consistent and use comments or add another folder for manual ones

**Comment by Stupremee** [comment]
Oh okay. That's much better

**Comment by RDambrosio016** [comment]
You can see examples on them in the expr.rs file, the comments with `// test ..` and `// test_err` comments

**Comment by Stupremee** [comment]
Oh god. These numbers are really annoying

**Comment by RDambrosio016** [comment]
Yeah thats why i removed them now, they dont really work out well for some reason

**Comment by Stupremee** [comment]
Yea. Please write a message if I can rebase and fix

**Comment by RDambrosio016** [comment]
Yeah you should be able to get the new test files, then:
- add a comment which starts with `// test_err something` and the source code of the test as comments after it
- run `cargo xtask codegen` to generate the tests
- run `$env:UPDATE_EXPECT = 1; cargo test` in rslint_parser (or non-powershell equivalent)

**Comment by RDambrosio016** [comment]
You should delete the old test file 👀

**Comment by RDambrosio016** [comment]
LGTM!

**Pull request merged**
