### PR TITLE
Update labels.rs (WIP)

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
update macro name

### CODE REVIEW

**Comment by RDambrosio016** [comment]
🤔 I dont get the reason for this change, first off, you would have to update tens of thousands of lines of code which use `T![..]`, and it would just be more boilerplate for little gain.

**Comment by RDambrosio016** [comment]
Ill go ahead and close this as it's too big of a breaking change for little to no gain.

**Comment by IWANABETHATGUY** [comment]
i dont't notice that you have use `Token` as a struct name, I Think `T` often used as a generic Type, so It's may be confused.

**Comment by RDambrosio016** [comment]
Thats not exactly the case considering generics dont have a `!` after it, `T!` is almost always called using square brackets, and finally, i do not know of any functions in the parser or lexer or core which take a `T` generic and also use `T!`

**Pull request closed without merging**
